"""sensor_id set null on sensor delete

Revision ID: 179f9f3bf4dd
Revises: 0006_add_external_event_id
Create Date: 2026-09-11 15:39:24.420800
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
revision: str = '179f9f3bf4dd'
down_revision: str | Sequence[str] | None = '0006_add_external_event_id'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor_events', 'sensor_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('sensor_events_ibfk_2'), 'sensor_events', type_='foreignkey')
    op.create_foreign_key(
        'fk_sensor_events_sensor_id_sensors',
        'sensor_events', 'sensors', ['sensor_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sensor_events_sensor_id_sensors', 'sensor_events', type_='foreignkey')
    op.create_foreign_key(
        'fk_sensor_events_sensor_id_sensors',
        'sensor_events', 'sensors', ['sensor_id'], ['id'], ondelete='CASCADE'
    )
    op.alter_column('sensor_events', 'sensor_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
